import { and, desc, eq, isNull, or, sql } from "drizzle-orm";
import { getDb, getPool } from "../connection";
import {
  agentJournal,
  agentPhases,
  agentPlans,
  agentSessions,
  agentState,
  agentTasks,
  atoms,
  busEvents,
  crmActivities,
  crmClients,
  crmOrderLines,
  crmOrders,
  crmProducts,
  crmRounds,
  crmTelesales,
  dags,
  dagNodes,
  expertEmbeddings,
  expertPatterns,
  gitProjects,
  gitTasks,
  globalContext,
  interactions,
  memoryArchive,
  memoryLive,
  projects,
  qubikCache,
  qubikFeedback,
  routines,
  routineLogs,
  sharedContexts,
  tasks,
  userAddons,
  voiceProfiles,
  webhookEvents,
  type ExpertDocumentRef,
  type NodeOutputJSON,
  type VoiceSampleRef,
} from "../schema";

export {
  and,
  desc,
  eq,
  getDb,
  getPool,
  isNull,
  or,
  sql,
  agentJournal,
  agentPhases,
  agentPlans,
  agentSessions,
  agentState,
  agentTasks,
  atoms,
  busEvents,
  crmActivities,
  crmClients,
  crmOrderLines,
  crmOrders,
  crmProducts,
  crmRounds,
  crmTelesales,
  dags,
  dagNodes,
  expertEmbeddings,
  expertPatterns,
  gitProjects,
  gitTasks,
  globalContext,
  interactions,
  memoryArchive,
  memoryLive,
  projects,
  qubikCache,
  qubikFeedback,
  routines,
  routineLogs,
  sharedContexts,
  tasks,
  userAddons,
  voiceProfiles,
  webhookEvents,
};

export type { ExpertDocumentRef, NodeOutputJSON, VoiceSampleRef };

export function genId(prefix = ""): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 8);
  return prefix ? `${prefix}-${ts}-${rand}` : `${ts}-${rand}`;
}

export const now = () => new Date().toISOString();
