/**
 * ubik-mcp HTTP gateway
 * Spawns each stdio server as subprocess, aggregates tools, exposes via SSE on :8902.
 * Generated by fleet — do not edit manually.
 */
export {}; // placeholder — to be implemented by agent-3
